version: 2
updates:
    - package-ecosystem: npm
      directory: 'client'
      schedule:
          interval: daily
          time: '21:00'
      open-pull-requests-limit: 10
    - package-ecosystem: npm
      directory: 'server'
      schedule:
          interval: daily
          time: '21:00'
      open-pull-requests-limit: 10
    - package-ecosystem: github-actions
      directory: '.github'
      schedule:
          interval: daily
          time: '21:00'
      open-pull-requests-limit: 10
